ITEMS = [
  {name: "Aspirin", photo: "aspirin.png", price: 1},
  {name: "Cliff Bar", photo: "cliff-bar.gif", price: 1},
  {name: "Kondome", photo: "condoms.png", price: 1},
  {name: "Evian", photo: "evian-bottle.png", price: 1},
  {name: "Extra Kaugummi", photo: "extra-gum.png", price: 1},
  {name: "Feuchttücher", photo: "feuchttücher.png", price: 1},
  {name: "Airwaves Kaugummi", photo: "airwaves-gum.png", price: 1},
  {name: "Hitschler", photo: "hitschler.png", price: 1},
  {name: "Ladekabel", photo: "iphone-kabel.png", price: 1},
  {name: "Knoppers", photo: "knoppers.png", price: 1},
  {name: "Milka", photo: "milka.png", price: 1},
  {name: "Nivea Creme", photo: "nivea.png", price: 1},
  {name: "Oreos", photo: "oreo.png", price: 1},
  {name: "Erdnüsee", photo: "peanuts.png", price: 1},
  {name: "Red Bull", photo: "red-bull.png", price: 1},
  {name: "Skittles", photo: "skittles.png", price: 1},
  {name: "Snickers", photo: "snickers.png", price: 1},
  {name: "Sonnencreme", photo: "sonnencreme.png", price: 1},
  {name: "Twix", photo: "twix.png", price: 1},
  {name: "Werthers Original", photo: "werthers.png", price: 1},
  {name: "Zahnbürste", photo: "zahnbürste.png", price: 1},
]
